driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.0.3
  data_path: test/shared

platforms:
- name: ubuntu-14.04
  run_list:
    - recipe[apt]

suites:
  - name: default
    run_list:
        - recipe[prometheus::default]
    attributes:
