AllCops:
  Exclude:
    - vendor/**
    - .kitchen/**

ClassLength:
  Enabled: false
Documentation:
  Enabled: false
Encoding:
  Enabled: false
LineLength:
  Enabled: false
MethodLength:
  Enabled: false
NumericLiterals:
  Enabled: false
Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes
Metrics/LineLength:
  Enabled: false
